# Generated by Django 5.0.1 on 2024-02-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard_app', '0002_alter_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='status',
        ),
    ]
