# Generated by Django 5.0.1 on 2024-02-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard_app', '0003_rename_approved_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('U', 'undefined'), ('A', 'approved'), ('R', 'rejected')], default='', max_length=20),
        ),
    ]
