# Generated by Django 5.0.1 on 2024-02-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard_app', '0005_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('undefined', 'undefined'), ('approved', 'approved'), ('rejected', 'rejected')], default='undefined', max_length=20),
        ),
    ]
